//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gruppa
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Студент.
    /// </summary>
    // *** Start programmer edit section *** (Студент CustomAttributes)

    // *** End programmer edit section *** (Студент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Студент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.Gruppa.Группа fГруппа;
        
        // *** Start programmer edit section *** (Студент CustomMembers)

        // *** End programmer edit section *** (Студент CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Студент.ФИО CustomAttributes)

        // *** End programmer edit section *** (Студент.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Студент.ФИО Get start)

                // *** End programmer edit section *** (Студент.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Студент.ФИО Get end)

                // *** End programmer edit section *** (Студент.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.ФИО Set start)

                // *** End programmer edit section *** (Студент.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Студент.ФИО Set end)

                // *** End programmer edit section *** (Студент.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Студент.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Группа CustomAttributes)

        // *** End programmer edit section *** (Студент.Группа CustomAttributes)
        [PropertyStorage(new string[] {
                "Группа"})]
        [NotNull()]
        public virtual IIS.Gruppa.Группа Группа
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Группа Get start)

                // *** End programmer edit section *** (Студент.Группа Get start)
                IIS.Gruppa.Группа result = this.fГруппа;
                // *** Start programmer edit section *** (Студент.Группа Get end)

                // *** End programmer edit section *** (Студент.Группа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Группа Set start)

                // *** End programmer edit section *** (Студент.Группа Set start)
                this.fГруппа = value;
                // *** Start programmer edit section *** (Студент.Группа Set end)

                // *** End programmer edit section *** (Студент.Группа Set end)
            }
        }
    }
}
